/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bankProject;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rowan
 */
public class JPanelEmployeeLogin extends javax.swing.JPanel {
    private JFrameMain frame;
    /**
     * Creates new form JPanelLogin
     */
    public JPanelEmployeeLogin(JFrameMain f) {
        frame=f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonUserSignin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneErrors = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log in to your account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel2.setText("Employee ID (full name if signing up):");
        jPanel2.add(jLabel2);

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldUsername);

        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jPanel2.add(jPasswordField1);

        jButtonLogin.setText("Log in");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonUserSignin.setText("Sign in as client");
        jButtonUserSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserSigninActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jTextPaneErrors.setEditable(false);
        jTextPaneErrors.setFocusable(false);
        jScrollPane1.setViewportView(jTextPaneErrors);

        jLabel4.setText("ID: 0987654321, Pass: my_pass");

        jButton1.setText("Sign up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUserSignin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLogin)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUserSignin)
                    .addComponent(jButtonExit)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        Path file = PathGetter.programResource("resources/users.txt");
        Path encrypt = PathGetter.programResource("resources/encrypt.txt");
        try(BufferedReader reader = Files.newBufferedReader(file)){
            String username=jTextFieldUsername.getText();
            //ensure the right username length
            if(username.length()!=10){
                jTextPaneErrors.setText("ID must be a 10 digit number");
                reader.close();
                return;
            }
            String password=new String(jPasswordField1.getPassword());
            List<String> encryptData = Files.readAllLines(encrypt);
            byte[] salt=encryptData.get(0).getBytes();
            int ittrs=Integer.parseInt(encryptData.get(1));
            byte[] hash=Credentials.hash(password, salt, ittrs);
            Base64.Decoder dec = Base64.getDecoder();
            String line;
            //for each user
            while((line=reader.readLine())!=null){
                //if the employee id matches the id in the current line
                if(username.equals(Credentials.employeeID(line)))
                    //if the passwords match
                    if(Arrays.equals(dec.decode(Credentials.password(line)),hash)){
                        //sign in with the employee's account
                        jTextPaneErrors.setText("logging in...");
                        Employee employee = new Employee(username);
                        frame.setPanel(new JPanelAccountCreator(frame,employee));
                    }else{
                        jTextPaneErrors.setText("The ID number or password is incorrect.");
                    }
                else
                    jTextPaneErrors.setText("The ID number or password is incorrect.");
            }
            reader.close();
        }catch(IOException ex){
            jTextPaneErrors.setText("A program error occurred.");
            System.err.println(ex);
        }catch(NumberFormatException ex){
            jTextPaneErrors.setText("ID must be a 10 digit number");
        }
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonUserSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserSigninActionPerformed
        frame.setPanel(new JPanelUserLogin(frame));
    }//GEN-LAST:event_jButtonUserSigninActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //load required files for encryption and ID info
        Path encryptFile = PathGetter.programResource("resources/encrypt.txt");
        Path bankData = PathGetter.programResource("resources/bankData.txt");
        Path usersFile = PathGetter.programResource("resources/users.txt");
        String name = jTextFieldUsername.getText();
        String passwordStr = new String(jPasswordField1.getPassword());
        //only continue if the fields are not empty
        if(name==null||passwordStr.length()==0){
            jTextPaneErrors.setText("Field is empty");
            return;
        }
        try {
            //index: 0: salt, 1:ittrs
            List<String> encrypt = Files.readAllLines(encryptFile);
            int ittrs = Integer.parseInt(encrypt.get(1));
            byte[] password = Credentials.hash(passwordStr, encrypt.get(0).getBytes(), ittrs);
            List<String> data = Files.readAllLines(bankData);
            //get next user/employee id number
            String employeeID = data.get(0);
            Long temp = Long.valueOf(employeeID);
            //get future id number
            Long newID = temp + 1;
            //ensure leading zeros
            int length=employeeID.length();
            for (int i = 0; i < (10 - length); i++) {
                employeeID = "0" + employeeID;
            }
            //rewrite the next ID number to the bankData file
            data.set(0, newID.toString());
            BufferedWriter writer = Files.newBufferedWriter(bankData, StandardOpenOption.TRUNCATE_EXISTING);
            for (String i : data) {
                writer.write(i);
                writer.newLine();
            }
            writer.close();
            //write the new employee's data to the users file
            String employeeText = Credentials.employeeText(employeeID, password, name);
            writer = Files.newBufferedWriter(usersFile, StandardOpenOption.APPEND);
            writer.write(employeeText);
            writer.newLine();
            writer.close();
            //display the new ID
            jTextPaneErrors.setText("New employee ID: " + employeeID);
        } catch (IOException | NumberFormatException ex) {
            Logger.getLogger(JPanelAccountCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonUserSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextPane jTextPaneErrors;
    // End of variables declaration//GEN-END:variables
}
